#!/bin/bash

function _mip_parseipr2(){
  if [ -n "$1" ]; then
    awk_pre_gsub="gsub(\" $1 \",\" [$1] \");"
  fi
  awk "{ $awk_pre_gsub gsub(\"/\",\" /\"); print \$2\":\t\"\$4\" \"\$5}"
}

function _mip_common(){
  if [ -n "$2" ]; then
    ip -f "$inetfamily" -o a s dev "$2"| _mip_parseipr2 | column -t | awk '{print "\t"$0}'
  else
    default_iface=$(awk '{ if ($2 == "00000000") {print $1; exit}}' /proc/net/route)
    inetfamily="$1"
    if [ "$UID" -eq "0" ]; then
        lsns -t net -n -uo NS,PID 2>/dev/null | while read id netns; do
        echo "NS: $id (pid $netns)"
        nsenter -t "$netns" -n ip -f "$inetfamily" -o a| _mip_parseipr2 | column -t | awk '{print "\t"$0}'
        echo
      done
    fi
  fi
  echo "NS: Current"
  ip -f "$inetfamily" -o a| _mip_parseipr2 "$default_iface"| column -t | awk '{print "\t"$0}'

}
function mip6(){
  _mip_common inet6 "$@"
}
function mip(){
  _mip_common inet "$@"
}

